import type { Collection } from './types';
import {dataBlock,svelteJSON} from './parsers';
export function normalize(name:string){return name.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ by lemonhaze.*$/,'').replace(/\(prints\)/g,'').replace(/1\/1s/g,'1 of 1s').replace(/[^a-z0-9]/g,'');}
const satAliases:Record<string,string>={"deprivation-prints-by-lemonhaze": "deprivation-by-lemonhaze", "trilogy-prints-by-lemonhaze": "prints-trilogy-by-lemonhaze", "portrait-2490-by-lemonhaze": "portrait-2490", "framed-by-lemonhaze": "framed", "mirage-prints-by-lemonhaze": "mirage-by-lemonhaze", "cypherville-by-lemonhaze": "cypherville-ordinals"};
export function ordCatalog(html:string):Collection[]{
 const map=new Map<string,Collection>();for(const m of html.matchAll(/\{dbId:"[^"\n]+",slug:"[^"\n]+",name:"[^"\n]*[Ll]emonhaze[^"\n]*"/g)){const raw=svelteJSON(dataBlock(html.slice(m.index),''));if(!raw.slug||!Number.isFinite(raw.supply))continue;const key=raw.slug;map.set(key,{key,name:raw.name,kind:/print|edition/i.test(raw.name)?'Prints & editions':/1 of 1/i.test(raw.name)?'1 of 1s':'Collection',image:raw.image||null,supply:raw.supply,refs:{ord:{id:key,url:`https://ord.net/collection/${key}`},satflow:{id:satAliases[key]||key,url:`https://www.satflow.com/ordinals/${satAliases[key]||key}`} ,ow:{id:key,url:`https://ordinalswallet.com/collection/${key}`}},stats:{ord:{listed:raw.listed,floor:raw.floor===null?null:Math.round(raw.floor*1e8),topOffer:raw.topOffer===null?null:Math.round(raw.topOffer*1e8)}}});}if(!map.size)throw Error('No Lemonhaze collections found in Ord.net page');return [...map.values()];
}
export function mergeGamma(catalog:Collection[],stats:any[]):Collection[]{const result=structuredClone(catalog);for(const s of stats){const g=s.collection;if(g?.chain!=='bitcoin'||g.creator_user_ref?.slug!=='lemonhaze')continue;const candidates=result.filter(c=>normalize(c.name)===normalize(g.name));let c=candidates.length===1?candidates[0]:undefined;
 // Explicit series aliases; inscription identity remains exact, never name-based.
 if(!c&&g.name==='Games (Manufactured) by Lemonhaze')c=result.find(x=>x.key==='games-by-lemonhaze');
 if(!c){c={key:`gamma-${g.id}`,name:g.name,kind:g.type==='print'?'Prints & editions':'Collection',image:g.collection_image_url||(/image/.test(g.content_type||'')?g.content_url:null),supply:g.stats?.total_items??null,refs:{}};result.push(c)}
 c.refs.gamma={id:g.id,url:new URL(g.location_url.trim(),'https://gamma.io').href,type:g.type};c.stats={...c.stats,gamma:{listed:s.current_secondary_listings_quantity??g.stats?.listed_count??null,floor:s.secondary_floor_price_token_amount?.unit==='sats'?s.secondary_floor_price_token_amount.amount:null,topOffer:s.current_best_offer_price_token_amount?.unit==='sats'?s.current_best_offer_price_token_amount.amount:null}};
 }return result;}
export function mergeWallet(catalog:Collection[],collections:any[]):Collection[]{const result=structuredClone(catalog);for(const g of collections){if(!g.name?.toLowerCase().includes('lemonhaze'))continue;const n=normalize(g.name).replace('miscelleneous','miscellaneous').replace('gamesmanufactured','games');let c=result.find(x=>normalize(x.name)===n);if(!c){c={key:`ow-${g.slug}`,name:g.name,kind:/print|edition/i.test(g.name)?'Prints & editions':'Collection',image:g.icon||null,supply:g.total_supply??null,refs:{}};result.push(c)}const old=c.refs.ow;const aliases=[...new Set([...(old?.aliases||[]),...(old?[old.id]:[]),g.slug])];c.refs.ow={id:old?.id||g.slug,url:old?.url||`https://ordinalswallet.com/collection/${g.slug}`,aliases};if(!c.refs.satflow)c.refs.satflow={id:g.slug,url:`https://www.satflow.com/ordinals/${g.slug}`};if(!c.image&&g.icon)c.image=g.icon;}return result;}
