import React, { useEffect, useMemo, useState } from 'react';
import {ArrowUpRight,RefreshCw,Search,Fingerprint,Info,ScanLine,ChevronRight,Copy,Check,Button,Input,Tabs,TabsList,TabsTrigger,TabsContent,Table,TableHeader,TableBody,TableRow,TableHead,TableCell,Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './market-ui';
import initial from './lib/initial.json';
import { markets, marketNames, resultKey, deduplicate, type Collection, type Market, type Snapshot, type Result } from './lib/types';
const btc=(s:number|null|undefined)=>s==null?'—':(s/1e8).toFixed(8).replace(/0+$/,'').replace(/\.$/,'');
const short=(s:string)=>s.slice(0,8)+'…'+s.slice(-7);
const displayName=(s:string)=>s.replace(/ by Lemonhaze.*$/,'');
function when(s:string){if(!s)return'Not scanned';return new Date(s).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});}
function Mark({market}:{market:Market}){return <span aria-hidden="true" className={`market-icon market-${markets.indexOf(market)}`}>{({ord:'O',gamma:'γ',satflow:'S',ow:'W'})[market]}</span>}
function Art({c}:{c:Collection}){return c.image?<img loading="lazy" src={c.image} alt="" onError={e=>{e.currentTarget.style.visibility='hidden'}}/>:<span className="art-fallback">{displayName(c.name).slice(0,1)}</span>}
export default function Home({apiBase='/api'}:{apiBase?:string}){
 const [data,setData]=useState<Snapshot>(initial as Snapshot);const [query,setQuery]=useState('');const [kind,setKind]=useState('all');const [sort,setSort]=useState('listed');const [tab,setTab]=useState('collections');const [limit,setLimit]=useState(12);const [active,setActive]=useState<Collection|null>(null);const [help,setHelp]=useState(false);const [running,setRunning]=useState(false);const [progress,setProgress]=useState({done:0,total:0});const [notice,setNotice]=useState('');const [copied,setCopied]=useState('');
 useEffect(()=>{fetch(apiBase+'/snapshot').then(async r=>{const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>setNotice(e.message));},[]);
 const allResults=Object.values(data.results);const resolved=useMemo(()=>deduplicate(Object.values(data.results)),[data.results]);const cross=resolved.filter(x=>x.observations.length>1);
 const latestCheck=allResults.map(r=>r.checkedAt).filter(Boolean).sort().at(-1);
 const appearances=allResults.reduce((a,r)=>a+(r.listed??0),0);const expected=data.catalog.reduce((n,c)=>n+Object.keys(c.refs).length,0);const good=allResults.filter(r=>r.status==='ok').length;const failures=allResults.filter(r=>r.status==='error').length;
 const total=(c:Collection)=>markets.reduce((n,m)=>n+(data.results[resultKey(c.key,m)]?.listed??0),0);
 const floor=(c:Collection)=>{const v=markets.map(m=>data.results[resultKey(c.key,m)]?.floor).filter((x):x is number=>typeof x==='number');return v.length?Math.min(...v):null;};
 const rows=data.catalog.filter(c=>(kind==='all'||c.kind===kind)&&c.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='floor'?(floor(a)??Infinity)-(floor(b)??Infinity):total(b)-total(a)||a.name.localeCompare(b.name));
 const crossRows=cross.filter(x=>`${x.name} ${x.id}`.toLowerCase().includes(query.toLowerCase()));
 const offers=allResults.filter(r=>(r.topOffer??0)>0).sort((a,b)=>(b.topOffer??0)-(a.topOffer??0)).filter(r=>(data.catalog.find(c=>c.key===r.key)?.name||'').toLowerCase().includes(query.toLowerCase()));
 async function scan(){if(running)return;setRunning(true);setNotice('Discovering collections and editions…');setProgress({done:0,total:0});let jobFailures=0,cachedJobs=0,satflowPaused=false;try{
  const response=await fetch(apiBase+'/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({discover:true})});const discovered=await response.json() as Pick<Snapshot,"catalog"|"discoveredAt"|"discoveryWarning"> & {error?:string};if(!response.ok)throw Error(discovered.error);setData(d=>({...d,...discovered}));
  const jobs=(discovered.catalog as Collection[]).flatMap(c=>markets.filter(m=>c.refs[m]).map(m=>({key:c.key,market:m})));setProgress({done:0,total:jobs.length});setNotice('Scanning public listings and offers. Keep this page open until the scan finishes.');
  const queues=[jobs.filter(j=>j.market==='satflow'),...Array.from({length:3},(_,i)=>jobs.filter(j=>j.market!=='satflow').filter((_,n)=>n%3===i))];
  await Promise.all(queues.map(async queue=>{for(const job of queue){try{const r=await fetch(apiBase+'/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(job)});const result=await r.json() as Result & {error?:string;cached?:boolean;cooldown?:boolean;scanNote?:string};if(!r.ok)throw Error(result.error);if(result.status==='error')jobFailures++;if(result.cached)cachedJobs++;setData(d=>({...d,results:{...d.results,[resultKey(job.key,job.market)]:result}}));if(job.market==='satflow'&&(result.cooldown||result.message.includes('HTTP 429'))){satflowPaused=true;break;}}catch{jobFailures++;}finally{setProgress(p=>({...p,done:p.done+1}));}if(job.market==='satflow')await new Promise(resolve=>setTimeout(resolve,2200));}}));
  setNotice(`Scan finished. ${jobFailures?`${jobFailures} source checks need attention; previous snapshots are retained.`:'Results saved.'}${cachedJobs?' Recent shared snapshots were reused.':''}${satflowPaused?' Satflow is cooling down; its remaining snapshots were retained.':''}${discovered.discoveryWarning?' '+discovered.discoveryWarning:''}`);
 }catch(e){setNotice(e instanceof Error?e.message:'Scan could not finish. Please retry.')}finally{setRunning(false)}}
 async function copy(id:string){try{await navigator.clipboard.writeText(id);setCopied(id);setTimeout(()=>setCopied(''),1800)}catch{setNotice('Copy unavailable. Open the marketplace link to view the full inscription ID.')}}
 function count(c:Collection,m:Market){const r=data.results[resultKey(c.key,m)];if(!c.refs[m])return <span className="unmapped" title="No verified collection mapping on this marketplace">—</span>;if(!r)return <span className="unmapped" title="Not scanned yet">—</span>;if(r.listed==null)return <span className="source-unavailable" title={r.message}>Unavailable</span>;return <button onClick={()=>setActive(c)} className={`listing-count ${r.listed>0?'has-listings':''} ${r.status==='error'?'stale-count':''}`} title={`${marketNames[m]} · ${when(r.checkedAt)}${r.status!=='ok'?' · '+r.message:''}`}>{r.listed}{r.status==='partial'?<sup>†</sup>:r.status==='error'?<sup>!</sup>:null}</button>}
 return <div className="shell"><header className="masthead"><a href="https://lemonhaze.com/" className="brand">LEMONHAZE<small>&lt;!-- ARTIST &amp; COUREUR DE BOIS --&gt;</small></a><nav className="site-nav" aria-label="Site navigation"><a href="https://lemonhaze.com/supply">Supply &amp; Marketplace</a><span aria-current="page">Market Watch</span></nav></header><main>
 <div className="heading"><div><div className="eyebrow">SUPPLY & MARKETPLACE / BITCOIN</div><h1>Market Watch</h1><p>Lemonhaze works across the secondary market.</p></div><div className="scan-wrap"><Button onClick={scan} disabled={running} className="scan-button"><RefreshCw size={17} className={running?'spin':''}/>{running?'Scanning…':'Scan now'}</Button><span>{running?(progress.total?`${progress.done} / ${progress.total} source checks`:'Finding collections…'):latestCheck?'Last checked '+when(latestCheck):'Refresh public listings'}</span></div></div>
 <div className="source-strip">{markets.map(m=>{const results=allResults.filter(r=>r.market===m);const checked=results.filter(r=>r.status==='ok').length;const errors=results.filter(r=>r.status==='error').length;const mapped=data.catalog.filter(c=>c.refs[m]).length;return <div className="source" key={m}><Mark market={m}/><div><strong>{marketNames[m]}</strong><small>{errors?`${errors} checks unavailable`:checked===mapped&&mapped?`${checked} collections scanned`:`${checked} / ${mapped} complete`}</small></div><a aria-label={`Open ${marketNames[m]}`} target="_blank" rel="noreferrer" href={m==='ord'?'https://ord.net/collections?sort=marketCap&q=lemonhaze':m==='gamma'?'https://gamma.io/lemonhaze/created':m==='satflow'?'https://www.satflow.com/':'https://ordinalswallet.com/'}><ArrowUpRight size={15}/></a></div>})}</div>
 <section className="metrics"><div><span>Collections & editions</span><b>{data.catalog.length}</b><small>Created by Lemonhaze</small></div><div><span>Listing appearances</span><b>{appearances}</b><small>Across saved market snapshots</small></div><div><span>Unique listed works</span><b>{resolved.length||'—'}</b><small>{good===expected?'Matched by inscription ID':'Resolved IDs · coverage incomplete'}</small></div><button className="metric-cross" onClick={()=>{setTab('duplicates');setQuery('')}}><span>Cross-listed works <ArrowUpRight size={14}/></span><b>{allResults.some(r=>r.checkedAt)?cross.length:'—'}<Fingerprint size={28}/></b><small>Same inscription, multiple markets</small></button></section>
 <div className={`coverage ${failures?'warning':''}`}><Info size={15}/><span>{running?notice:`${good} of ${expected} collection checks complete.${failures?` ${failures} unavailable.`:''} ${good===expected?'Snapshots are not a real-time orderbook.':'Partial or stale sources are marked below.'}`}</span><button onClick={()=>setHelp(true)}>How counts work</button></div>
 {notice&&!running&&<div className="notice" role="status">{notice}</div>}{running&&<div className="scan-progress" role="progressbar" aria-label="Scan progress" aria-valuemin={0} aria-valuemax={progress.total||100} aria-valuenow={progress.done}><div style={{width:`${progress.total?progress.done/progress.total*100:2}%`}}/></div>}
 <Tabs value={tab} onValueChange={v=>{setTab(v);setLimit(12)}}><div className="table-toolbar"><TabsList variant="line"><TabsTrigger value="collections">Collections <span className="count">{data.catalog.length}</span></TabsTrigger><TabsTrigger value="duplicates">Cross-listed <span className="count">{cross.length}</span></TabsTrigger><TabsTrigger value="bids">Offers</TabsTrigger></TabsList><div className="search"><Search size={16}/><Input aria-label="Search collections or inscriptions" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12)}} placeholder={tab==='duplicates'?'Find an inscription…':'Find a collection…'}/></div></div>
 <TabsContent value="collections"><div className="filters"><div className="kind-filter">{['all','Collection','Prints & editions','1 of 1s'].map(k=><button key={k} aria-pressed={kind===k} className={kind===k?'selected':''} onClick={()=>{setKind(k);setLimit(12)}}>{k==='all'?'All works':k==='Collection'?'Collections':k}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort collections" className="sort-select"><option value="listed">Most listed</option><option value="name">Name A–Z</option><option value="floor">Lowest floor</option></select></div>
 <Table><TableHeader><TableRow><TableHead>COLLECTION / EDITION</TableHead><TableHead>ORD.NET</TableHead><TableHead>GAMMA</TableHead><TableHead>SATFLOW</TableHead><TableHead>ORDINALS WALLET</TableHead><TableHead>FLOOR · BTC</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{rows.slice(0,limit).map(c=><TableRow key={c.key}><TableCell><button className="collection" onClick={()=>setActive(c)}><Art c={c}/><div><strong>{displayName(c.name)}</strong><small>{c.kind} <span>·</span> {c.supply??'Unknown'} inscriptions</small></div></button></TableCell>{markets.map(m=><TableCell key={m}>{count(c,m)}</TableCell>)}<TableCell className="mono">{btc(floor(c))}</TableCell><TableCell><button className="open-row" aria-label={`View ${c.name}`} onClick={()=>setActive(c)}><ChevronRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<div className="empty"><Search/><h2>No matching works</h2><p>Try another collection name or filter.</p></div>}<div className="table-bottom"><span>Showing {Math.min(limit,rows.length)} of {rows.length} works <span className="legend">† Partial data · ! Last successful snapshot · — Not mapped / scanned</span></span>{limit<rows.length&&<Button variant="outline" onClick={()=>setLimit(l=>l+20)}>Show more</Button>}</div></TabsContent>
 <TabsContent value="duplicates"><div className="section-note"><Fingerprint size={17}/><span>{cross.length} inscriptions appear on more than one marketplace. Each counts as one unique work.</span></div>{!crossRows.length?<div className="empty"><Fingerprint/><h2>{cross.length?'No matching inscriptions':'No cross-listings resolved yet'}</h2><p>{good<expected?'Run a scan to complete the inscription comparison. Missing coverage does not mean no duplicates.':'No exact inscription ID appears in more than one saved marketplace snapshot.'}</p></div>:<div className="duplicate-list">{crossRows.map(x=><article className="duplicate" key={x.id}><div className="duplicate-title"><div><h2>{x.name}</h2><button className="copy-id mono" onClick={()=>copy(x.id)} title={x.id}>{short(x.id)} {copied===x.id?<Check size={13}/>:<Copy size={13}/>}</button></div><span className="cross-badge">{x.observations.length} markets / 1 work</span></div><div className="duplicate-markets">{x.observations.map(o=><a key={o.market} href={o.url} target="_blank" rel="noreferrer"><Mark market={o.market}/><div><strong>{marketNames[o.market]}</strong><span className="mono">{btc(o.price)} BTC</span><small>Checked {when(o.checkedAt)}</small></div><ArrowUpRight size={15}/></a>)}</div><small className="duplicate-foot">Exact inscription match. Shared marketplace orders may appear more than once.</small></article>)}</div>}</TabsContent>
 <TabsContent value="bids"><div className="section-note"><Info size={17}/><span>Public top offers and Satflow bid counts. Private offers and complete bid histories are not available from every source.</span></div>{!offers.length?<div className="empty"><ScanLine/><h2>No public top offers in this snapshot</h2><p>Run a scan to check available offer feeds. An unavailable feed is not a zero-bid result.</p></div>:<Table><TableHeader><TableRow><TableHead>COLLECTION</TableHead><TableHead>MARKET</TableHead><TableHead>TOP OFFER · BTC</TableHead><TableHead>PUBLIC BIDS</TableHead><TableHead>CHECKED</TableHead></TableRow></TableHeader><TableBody>{offers.map(r=>{const c=data.catalog.find(c=>c.key===r.key);if(!c)return null;return <TableRow key={resultKey(r.key,r.market)}><TableCell><button className="collection" onClick={()=>setActive(c)}><Art c={c}/><strong>{displayName(c.name)}</strong></button></TableCell><TableCell>{marketNames[r.market]}</TableCell><TableCell className="mono">{btc(r.topOffer)}</TableCell><TableCell>{r.offerCount??'Not exposed'}</TableCell><TableCell><a className="offer-link" href={c.refs[r.market]?.url} target="_blank" rel="noreferrer">{when(r.checkedAt)}{r.status==='error'?' · stale':''}<ArrowUpRight size={14}/></a></TableCell></TableRow>})}</TableBody></Table>}</TabsContent></Tabs>
 <footer><span><ScanLine size={15}/> Public market snapshots · All prices in BTC</span><span>LEMONHAZE / MARKET WATCH</span></footer>
 <Sheet open={!!active} onOpenChange={o=>!o&&setActive(null)}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{active?displayName(active.name):''}</SheetTitle><SheetDescription>{active?.kind} · {active?.supply} inscriptions. Marketplace prices may include different fees.</SheetDescription></SheetHeader><div className="detail-body">{active&&markets.map(m=>{const ref=active.refs[m],r=data.results[resultKey(active.key,m)];return <section className="detail-market" key={m}><div className="detail-market-heading"><Mark market={m}/><h3>{marketNames[m]}</h3>{ref&&<a href={ref.url} target="_blank" rel="noreferrer">Open <ArrowUpRight size={14}/></a>}</div>{!ref?<p>No verified collection mapping on this marketplace.</p>:!r?<p>Run a scan to check this collection.</p>:<><div className="detail-stats"><span><strong>{r.listed??'—'}</strong> listings</span><span>Floor <strong>{btc(r.floor)} BTC</strong></span><span>Top offer <strong>{btc(r.topOffer)} BTC</strong></span></div><p className="checked">{r.checkedAt?'Captured '+when(r.checkedAt):'No successful scan'}{r.status==='error'?' · Refresh failed':''}</p>{r.message&&<p className={r.status==='error'?'detail-warning':'detail-note'}>{r.message}</p>}{r.bids?.map(b=><div className="detail-bid" key={b.id}><div><strong>{b.scope==='collection'?'Collection bid':'Inscription bid'}</strong><small>{b.inscriptionId?short(b.inscriptionId):'Applies to the collection'}</small><small>{b.expiresAt?'Expires '+when(b.expiresAt):'Expiry not exposed'}</small></div><span className="mono">{btc(b.price)} BTC</span></div>)}{r.listings.map(l=><div className="detail-listing" key={l.id}><div><a href={l.url} target="_blank" rel="noreferrer">{l.name} <ArrowUpRight size={13}/></a><button className="copy-id mono" onClick={()=>copy(l.id)} title={l.id}>{short(l.id)} {copied===l.id?<Check size={12}/>:<Copy size={12}/>}</button>{l.origin&&<small>Reported origin: {marketNames[l.origin as Market]||l.origin}</small>}</div><span className="mono">{btc(l.price)} BTC</span></div>)}</>}</section>})}</div></SheetContent></Sheet>
 <Sheet open={help} onOpenChange={setHelp}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Reading the market</SheetTitle><SheetDescription>What the numbers include, and what they don’t.</SheetDescription></SheetHeader><div className="help-body"><h3>Appearances versus unique works</h3><p>Listing appearances add the counts visible on each market. Unique listed works count each exact inscription ID once, even if it appears in several collections or marketplaces. A different edition has a different ID.</p><h3>Shared orders</h3><p>Some marketplaces distribute the same order. A cross-listing flag means the same inscription is visible in multiple places; it does not prove the seller created independent orders. Source attribution is shown when available.</p><h3>On-demand snapshots</h3><p>Scan now discovers works on the Ord.net and Gamma creator pages, and Ordinals Wallet, then checks each mapped marketplace. Shared snapshots are saved between visits. Recent checks are reused for up to five minutes to limit repeat requests. Keep this page open during a scan. Marketplaces can cache data or change their public feeds.</p><h3>Unknown is not zero</h3><p>Zero means the source returned no active listings. A dash means no verified mapping or no scan yet. A dagger (†) means incomplete data. If a source fails, its previous snapshot is marked stale and excluded from inscription deduplication until refreshed.</p><h3>Coverage</h3><p>Collection mappings use known slugs and normalized collection titles. Unmatched prints remain separate rows. Duplicate detection itself uses exact inscription IDs only. Lots, auctions, private offers, unmapped works, and unavailable feeds can leave gaps. Totals are not a guarantee of immediately purchasable inventory.</p><p>Offers shows public top-offer summaries and the bids returned by Satflow. It is not a complete history of every bid on every artwork.</p></div></SheetContent></Sheet>
 </main></div>
}
